### ISSUE TITLE
`tox -e build-json-schemas` does not work as expected

### ISSUE THREAD

**Issue by NucciTheBoss** [canonical/charm-relation-interfaces#60] opened 2023-04-11 17:00 UTC
It does not seem that the new `build-json-schemas` tox env is working correctly. I am currently working on adding the `nfs-share` integration specification to this repository and when I run `tox -e build-json-schemas` as a pre-commit hook it overwrites the `requirer.json` and `provider.json` file for the ingress integration:

### Provider

![image](https://user-images.githubusercontent.com/40342202/231235201-c0061373-b38a-48ff-adea-a3a26d26543d.png)

### Requirer

![image](https://user-images.githubusercontent.com/40342202/231235337-dd7f7fe1-5604-4cbd-b223-34ab0e837464.png)

This issue is causing the CI jobs to fail on [my pull request](https://github.com/canonical/charm-relation-interfaces/actions/runs/4669580247/jobs/8268221452?pr=58).

**Comment by simskij** [comment] 2023-04-11 18:19
@PietroPasotti maybe?

**Comment by PietroPasotti** [comment] 2023-04-12 08:11
There is an issue with the importer code. The fix could be this simple:
https://github.com/PietroPasotti/interface-tester-pytest/pull/1
will test it later and report back or if @NucciTheBoss wants to give it a try...

**Comment by PietroPasotti** [comment] 2023-04-12 12:23
Should be fixed. refresh the interface-tester-pytest dependency to confirm

**Comment by NucciTheBoss** [comment] 2023-04-12 15:41
@PietroPasotti I am not seeing any changes after refreshing the dependency. Same behavior is present where nfs-share overwrites ingress.

**Comment by PietroPasotti** [comment] 2023-04-12 17:34
will check again tomorrow

**Comment by PietroPasotti** [comment] 2023-04-14 07:46
I just tried again and can't reproduce. How did you refresh the dependency? 
If your pre-commit is running `tox -e build-json-schemas`, the tox env might be cached still. 
Either run `tox -re build-json-schemas` manually to refresh the env, or do `rm -rf ./.tox` before you commit.

**Comment by NucciTheBoss** [comment] 2023-04-14 15:52
Are you building the JSON schemas using the new builder proposed in https://github.com/canonical/charm-relation-interfaces/pull/63? If so, I tried pulling `interface_tester` from your personal GitHub in my local fork but that did not work. For context, my fork is still using the _build.py_ file in _docs_ since https://github.com/canonical/charm-relation-interfaces/pull/63 has not landed yet. If this pull request contains the fix, I can wait for it to land and then rebase.

**Comment by PietroPasotti** [comment] 2023-04-17 07:08
Aha, yes, that could very well be. I merged the fix into `interface-tester-pytest` but that is only used in build.py since #63.

**Comment by PietroPasotti** [comment] 2023-04-18 07:52
Now that #63 is merged, can you try again and see if the issue persists? I tried retriggering the job but it still fails, probably because you need to rebase

**Closed** 2023-04-21 07:57 UTC
